name: Deploy Supabase Migrations

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'supabase/migrations/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
      SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Link to Supabase project
        run: |
          supabase link --project-ref $SUPABASE_PROJECT_ID

      - name: Run migrations
        run: |
          supabase db push

      - name: Notification on success
        if: success()
        run: |
          echo "✅ Migrations deployed successfully to Supabase!"

      - name: Notification on failure
        if: failure()
        run: |
          echo "❌ Failed to deploy migrations to Supabase"
          exit 1

